FROM ubuntu:22.04 as build
COPY ./src/ /src
WORKDIR /src
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libc6-dev \
    make
RUN make libnvshare.so

FROM 12.4.1-runtime-ubuntu22.04

COPY --from=build /src/libnvshare.so /libnvshare.so
ENV LD_PRELOAD=/libnvshare.so

COPY cuda-matmul.cu /cuda-matmul.cu

RUN nvcc -o /cuda-matmul /cuda-matmul.cu

ENTRYPOINT ["/cuda-matmul"]