apiVersion: v1
kind: Service
metadata:
  name: nvshare-metrics
  namespace: nvshare-system
  labels:
    app: nvshare-device-plugin
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    name: nvshare-device-plugin
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP