name: Build device plugin image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build-and-upload-image.yaml
    with:
      actor: ${{ github.actor }}
      dockerfile: Dockerfile.device_plugin
      imageTag: device-plugin-latest
    secrets:
      ghToken: ${{ secrets.GITHUB_TOKEN }}
