name: Build scheduler image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build-and-upload-image.yaml
    with:
      actor: ${{ github.actor }}
      dockerfile: Dockerfile.scheduler
      imageName: nvshare-scheduler
      imageTag: latest
    secrets:
      ghToken: ${{ secrets.GITHUB_TOKEN }}
